# Site settings
title: Sweet Life of Dana
email: dyakoobinsky@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Taking on the world of desserts, one dish at a time.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: swtlifeofdana
instagram_username:  swtlifeofdana

# Build settings
markdown: kramdown
